In [1]:
from faker import Faker
import pandas as pd
from datetime import datetime
import dataframe_image as dfi

In [2]:
fake = Faker("ru_RU")

In [3]:
n_samples = 4000

In [4]:
names = [fake.name() for _ in range(int(0.9 * n_samples))]
names.extend([fake.first_name() + ' ' + fake.last_name() for _ in range(int(0.1 * n_samples))])

phone_numbers = [fake.phone_number() for _ in range(n_samples)]

emails = [fake.ascii_email() for _ in range(n_samples)]

addresses = [fake.address() for _ in range(n_samples)]

credit_cards = [fake.credit_card_number() for _ in range(n_samples)]

for i in range(int(0.8 * n_samples), n_samples):
    num = credit_cards[i]
    credit_cards[i] = num[:4] + ' ' + num[4:8] + ' ' + num[8:12] + ' ' + num[12:]

security_codes = [fake.credit_card_security_code() for _ in range(n_samples)]

dates = [fake.date(pattern = '%Y-%m-%d', end_datetime = datetime.strptime('2016-05-24', '%Y-%m-%d')) 
               for _ in range(int(0.8 * n_samples))]
dates.extend([fake.date(pattern = '%Y/%m/%d', end_datetime = datetime.strptime('2016/05/24', '%Y/%m/%d')) 
               for _ in range(int(0.1 * n_samples))])
dates.extend([fake.date(pattern = '%B %d, %Y', end_datetime = datetime.strptime('May 24, 2016', '%B %d, %Y')) 
               for _ in range(int(0.1 * n_samples))])

In [5]:
pii_df = pd.DataFrame({'name': names, 
                       'phone_number': phone_numbers, 
                       'email': emails,
                       'address': addresses, 
                       'credit_card': credit_cards, 
                       'security_code': security_codes, 
                       'date': dates})

In [6]:
# pii_df.loc[[0, 1005, 2005, 3580, 3650], :]
# dfi.export(pii_df.loc[[0, 1005, 2005, 3580, 3650], :], 'sample_pii.png')
pii_df.sample(10)

,name,phone_number,email,address,credit_card,security_code,date
3637,Афанасий Орехов,8 589 965 0523,maksimiljan_88@oao.edu,"д. Ербогачен, наб. Смирнова, д. 38 к. 3, 244450",2704 4240 4817 5480,155,"January 10, 2010"
292,Макарова Феврония Владиславовна,8 (285) 710-3206,ladimir2014@yandex.ru,"п. Красноуфимск, алл. Белинского, д. 8 стр. 85...",6546631967630088,336,1992-08-05
947,Шубина Екатерина Романовна,8 (960) 030-72-03,martinoviosif@rambler.ru,"д. Выборг, наб. Береговая, д. 90, 831416",2256647401486514,761,1996-05-15
2960,Горбунова Наина Тимофеевна,8 (328) 636-62-51,uljan_15@mail.ru,"ст. Бирск, пер. 50 лет ВЛКСМ, д. 9/1 к. 8/3, 8...",376978995456822,485,2015-08-23
2607,Валерия Максимовна Копылова,+76568481132,lukjan_58@taif-nk.edu,"к. Когалым, наб. Дачная, д. 4, 298768",4474835279030975,895,1993-08-13
2870,Терентьева Екатерина Леонидовна,8 967 174 5937,fedorovereme@yahoo.com,"г. Саратов, алл. Толбухина, д. 45 к. 978, 944765",377060041981472,050,1996-04-15
3164,Ефимова Октябрина Львовна,8 (204) 301-82-48,elizar08@zao.com,"с. Тырныауз, ул. Поселковая, д. 3 к. 4/9, 147981",341612542614672,125,1997-01-02
1761,Мамонтова Алина Святославовна,8 253 947 4743,gorde_09@gmail.com,"с. Нижневартовск, алл. Мирная, д. 5 к. 351, 58...",4893534639848944,136,2015-08-09
3669,Степан Терентьев,+7 626 782 2421,samsonovsvjatopolk@mail.ru,"клх Калач-на-Дону, ул. Чайкиной, д. 750, 535765",3731 6309 7503 424,049,"July 24, 1984"
3888,Леонтий Евсеев,+7 (788) 136-2727,evseevsolomon@gmail.com,"к. Жигулевск, алл. Некрасова, д. 1/9 стр. 12, ...",3798 9705 1685 487,361,"December 31, 1989"

In [7]:
pii_df.to_csv('pii_data.csv', index=False, encoding='utf-8')